package net.aqualoco.sec.network;

public enum ServerConfigField {
    SLEEP_WEATHER_CLEAR_CHANCE_PERCENT,
    SLEEP_ANIMATION_DURATION_MULTIPLIER,
    FALL_ASLEEP_DELAY_TICKS,
    OVERRIDE_OVERLAY_TEXT,
    OVERLAY_CUSTOM_TEXT,
    SLEEP_ELIGIBILITY,
    MADE_IN_HEAVEN_CHANCE_PERCENT,
    WORLD_SLEEP_ACCELERATION_MODE,
    WORLD_SLEEP_AUTOMATIC_MODE,
    WORLD_SLEEP_ACCELERATION_PLAYERS_AFFECTED,
    MANUAL_ACCELERATION_RADIUS_CHUNKS,
    MANUAL_ACCELERATION_SPEED_PERCENT,
    GRASS_AND_FOLIAGE_ACCELERATION_ENABLED,
    CROPS_AND_SAPLINGS_ACCELERATION_ENABLED,
    KELP_ACCELERATION_ENABLED,
    VANILLA_ONLY_ACCELERATION,
    PROCESSES_ACCELERATION_ENABLED,
    PROCESSES_SPEED_PERCENT,
    BETTER_DAYS_COMPATIBILITY_ENABLED
}
